//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 08:58:06 PM AST 
//


package net.openkoncept.vroom.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="eventTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="onclick"/>
 *     &lt;enumeration value="ondblclick"/>
 *     &lt;enumeration value="onmousedown"/>
 *     &lt;enumeration value="onmouseup"/>
 *     &lt;enumeration value="onmouseover"/>
 *     &lt;enumeration value="onmousemove"/>
 *     &lt;enumeration value="onmouseout"/>
 *     &lt;enumeration value="onkeypress"/>
 *     &lt;enumeration value="onkeydown"/>
 *     &lt;enumeration value="onkeyup"/>
 *     &lt;enumeration value="onload"/>
 *     &lt;enumeration value="onunload"/>
 *     &lt;enumeration value="onabort"/>
 *     &lt;enumeration value="onerror"/>
 *     &lt;enumeration value="onresize"/>
 *     &lt;enumeration value="onscroll"/>
 *     &lt;enumeration value="onselect"/>
 *     &lt;enumeration value="onchange"/>
 *     &lt;enumeration value="onsubmit"/>
 *     &lt;enumeration value="onreset"/>
 *     &lt;enumeration value="onfocus"/>
 *     &lt;enumeration value="onblur"/>
 *     &lt;enumeration value="ondomfocusin"/>
 *     &lt;enumeration value="ondomfocusout"/>
 *     &lt;enumeration value="ondomactivate"/>
 *     &lt;enumeration value="onsubtreemodified"/>
 *     &lt;enumeration value="onnodeinserted"/>
 *     &lt;enumeration value="onnoderemoved"/>
 *     &lt;enumeration value="ondomnoderemovedfromdocument"/>
 *     &lt;enumeration value="ondomnodeinsertedintodocument"/>
 *     &lt;enumeration value="onattrmodified"/>
 *     &lt;enumeration value="oncharacterdatamodified"/>
 *     &lt;enumeration value="ms-oncut"/>
 *     &lt;enumeration value="ms-oncopy"/>
 *     &lt;enumeration value="ms-onpaste"/>
 *     &lt;enumeration value="ms-onbeforecut"/>
 *     &lt;enumeration value="ms-onbeforecopy"/>
 *     &lt;enumeration value="ms-onbeforepaste"/>
 *     &lt;enumeration value="ms-onafterupdate"/>
 *     &lt;enumeration value="ms-onbeforeupdate"/>
 *     &lt;enumeration value="ms-oncellchange"/>
 *     &lt;enumeration value="ms-ondataavailable"/>
 *     &lt;enumeration value="ms-ondatasetchanged"/>
 *     &lt;enumeration value="ms-ondatasetcomplete"/>
 *     &lt;enumeration value="ms-onerrorupdate"/>
 *     &lt;enumeration value="ms-onrowenter"/>
 *     &lt;enumeration value="ms-onrowexit"/>
 *     &lt;enumeration value="ms-onrowsdeleted"/>
 *     &lt;enumeration value="ms-onrowinserted"/>
 *     &lt;enumeration value="ms-oncontextmenu"/>
 *     &lt;enumeration value="ms-ondrag"/>
 *     &lt;enumeration value="ms-ondragstart"/>
 *     &lt;enumeration value="ms-ondragenter"/>
 *     &lt;enumeration value="ms-ondragover"/>
 *     &lt;enumeration value="ms-ondragleave"/>
 *     &lt;enumeration value="ms-ondragend"/>
 *     &lt;enumeration value="ms-ondrop"/>
 *     &lt;enumeration value="ms-onselectstart"/>
 *     &lt;enumeration value="ms-onhelp"/>
 *     &lt;enumeration value="ms-onbeforeunload"/>
 *     &lt;enumeration value="ms-onstop"/>
 *     &lt;enumeration value="ms-onbeforeeditfocus"/>
 *     &lt;enumeration value="ms-onstart"/>
 *     &lt;enumeration value="ms-onfinish"/>
 *     &lt;enumeration value="ms-onbounce"/>
 *     &lt;enumeration value="ms-onbeforeprint"/>
 *     &lt;enumeration value="ms-onafterprint"/>
 *     &lt;enumeration value="ms-onpropertychange"/>
 *     &lt;enumeration value="ms-onfilterchange"/>
 *     &lt;enumeration value="ms-onreadystatechange"/>
 *     &lt;enumeration value="ms-onlosecapture"/>
 *     &lt;enumeration value="xul-DOMMouseScroll"/>
 *     &lt;enumeration value="xul-ondragdrop"/>
 *     &lt;enumeration value="xul-ondragenter"/>
 *     &lt;enumeration value="xul-ondragexit"/>
 *     &lt;enumeration value="xul-ondraggesture"/>
 *     &lt;enumeration value="xul-ondragover"/>
 *     &lt;enumeration value="xul-CheckboxStateChange"/>
 *     &lt;enumeration value="xul-RadioStateChange"/>
 *     &lt;enumeration value="xul-onclose"/>
 *     &lt;enumeration value="xul-oncommand"/>
 *     &lt;enumeration value="xul-oninput"/>
 *     &lt;enumeration value="xul-DOMMenuItemActive"/>
 *     &lt;enumeration value="xul-DOMMenuItemInactive"/>
 *     &lt;enumeration value="xul-oncontextmenu"/>
 *     &lt;enumeration value="xul-onoverflow"/>
 *     &lt;enumeration value="xul-onoverflowchanged"/>
 *     &lt;enumeration value="xul-onunderflow"/>
 *     &lt;enumeration value="xul-onpopuphidden"/>
 *     &lt;enumeration value="xul-onpopuphiding"/>
 *     &lt;enumeration value="xul-onpopupshowing"/>
 *     &lt;enumeration value="xul-onpopupshown"/>
 *     &lt;enumeration value="xul-onbroadcast"/>
 *     &lt;enumeration value="xul-oncommandupdate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "eventTypeList")
@XmlEnum
public enum EventTypeList {

    @XmlEnumValue("onclick")
    ONCLICK("onclick"),
    @XmlEnumValue("ondblclick")
    ONDBLCLICK("ondblclick"),
    @XmlEnumValue("onmousedown")
    ONMOUSEDOWN("onmousedown"),
    @XmlEnumValue("onmouseup")
    ONMOUSEUP("onmouseup"),
    @XmlEnumValue("onmouseover")
    ONMOUSEOVER("onmouseover"),
    @XmlEnumValue("onmousemove")
    ONMOUSEMOVE("onmousemove"),
    @XmlEnumValue("onmouseout")
    ONMOUSEOUT("onmouseout"),
    @XmlEnumValue("onkeypress")
    ONKEYPRESS("onkeypress"),
    @XmlEnumValue("onkeydown")
    ONKEYDOWN("onkeydown"),
    @XmlEnumValue("onkeyup")
    ONKEYUP("onkeyup"),
    @XmlEnumValue("onload")
    ONLOAD("onload"),
    @XmlEnumValue("onunload")
    ONUNLOAD("onunload"),
    @XmlEnumValue("onabort")
    ONABORT("onabort"),
    @XmlEnumValue("onerror")
    ONERROR("onerror"),
    @XmlEnumValue("onresize")
    ONRESIZE("onresize"),
    @XmlEnumValue("onscroll")
    ONSCROLL("onscroll"),
    @XmlEnumValue("onselect")
    ONSELECT("onselect"),
    @XmlEnumValue("onchange")
    ONCHANGE("onchange"),
    @XmlEnumValue("onsubmit")
    ONSUBMIT("onsubmit"),
    @XmlEnumValue("onreset")
    ONRESET("onreset"),
    @XmlEnumValue("onfocus")
    ONFOCUS("onfocus"),
    @XmlEnumValue("onblur")
    ONBLUR("onblur"),
    @XmlEnumValue("ondomfocusin")
    ONDOMFOCUSIN("ondomfocusin"),
    @XmlEnumValue("ondomfocusout")
    ONDOMFOCUSOUT("ondomfocusout"),
    @XmlEnumValue("ondomactivate")
    ONDOMACTIVATE("ondomactivate"),
    @XmlEnumValue("onsubtreemodified")
    ONSUBTREEMODIFIED("onsubtreemodified"),
    @XmlEnumValue("onnodeinserted")
    ONNODEINSERTED("onnodeinserted"),
    @XmlEnumValue("onnoderemoved")
    ONNODEREMOVED("onnoderemoved"),
    @XmlEnumValue("ondomnoderemovedfromdocument")
    ONDOMNODEREMOVEDFROMDOCUMENT("ondomnoderemovedfromdocument"),
    @XmlEnumValue("ondomnodeinsertedintodocument")
    ONDOMNODEINSERTEDINTODOCUMENT("ondomnodeinsertedintodocument"),
    @XmlEnumValue("onattrmodified")
    ONATTRMODIFIED("onattrmodified"),
    @XmlEnumValue("oncharacterdatamodified")
    ONCHARACTERDATAMODIFIED("oncharacterdatamodified"),
    @XmlEnumValue("ms-oncut")
    MS_ONCUT("ms-oncut"),
    @XmlEnumValue("ms-oncopy")
    MS_ONCOPY("ms-oncopy"),
    @XmlEnumValue("ms-onpaste")
    MS_ONPASTE("ms-onpaste"),
    @XmlEnumValue("ms-onbeforecut")
    MS_ONBEFORECUT("ms-onbeforecut"),
    @XmlEnumValue("ms-onbeforecopy")
    MS_ONBEFORECOPY("ms-onbeforecopy"),
    @XmlEnumValue("ms-onbeforepaste")
    MS_ONBEFOREPASTE("ms-onbeforepaste"),
    @XmlEnumValue("ms-onafterupdate")
    MS_ONAFTERUPDATE("ms-onafterupdate"),
    @XmlEnumValue("ms-onbeforeupdate")
    MS_ONBEFOREUPDATE("ms-onbeforeupdate"),
    @XmlEnumValue("ms-oncellchange")
    MS_ONCELLCHANGE("ms-oncellchange"),
    @XmlEnumValue("ms-ondataavailable")
    MS_ONDATAAVAILABLE("ms-ondataavailable"),
    @XmlEnumValue("ms-ondatasetchanged")
    MS_ONDATASETCHANGED("ms-ondatasetchanged"),
    @XmlEnumValue("ms-ondatasetcomplete")
    MS_ONDATASETCOMPLETE("ms-ondatasetcomplete"),
    @XmlEnumValue("ms-onerrorupdate")
    MS_ONERRORUPDATE("ms-onerrorupdate"),
    @XmlEnumValue("ms-onrowenter")
    MS_ONROWENTER("ms-onrowenter"),
    @XmlEnumValue("ms-onrowexit")
    MS_ONROWEXIT("ms-onrowexit"),
    @XmlEnumValue("ms-onrowsdeleted")
    MS_ONROWSDELETED("ms-onrowsdeleted"),
    @XmlEnumValue("ms-onrowinserted")
    MS_ONROWINSERTED("ms-onrowinserted"),
    @XmlEnumValue("ms-oncontextmenu")
    MS_ONCONTEXTMENU("ms-oncontextmenu"),
    @XmlEnumValue("ms-ondrag")
    MS_ONDRAG("ms-ondrag"),
    @XmlEnumValue("ms-ondragstart")
    MS_ONDRAGSTART("ms-ondragstart"),
    @XmlEnumValue("ms-ondragenter")
    MS_ONDRAGENTER("ms-ondragenter"),
    @XmlEnumValue("ms-ondragover")
    MS_ONDRAGOVER("ms-ondragover"),
    @XmlEnumValue("ms-ondragleave")
    MS_ONDRAGLEAVE("ms-ondragleave"),
    @XmlEnumValue("ms-ondragend")
    MS_ONDRAGEND("ms-ondragend"),
    @XmlEnumValue("ms-ondrop")
    MS_ONDROP("ms-ondrop"),
    @XmlEnumValue("ms-onselectstart")
    MS_ONSELECTSTART("ms-onselectstart"),
    @XmlEnumValue("ms-onhelp")
    MS_ONHELP("ms-onhelp"),
    @XmlEnumValue("ms-onbeforeunload")
    MS_ONBEFOREUNLOAD("ms-onbeforeunload"),
    @XmlEnumValue("ms-onstop")
    MS_ONSTOP("ms-onstop"),
    @XmlEnumValue("ms-onbeforeeditfocus")
    MS_ONBEFOREEDITFOCUS("ms-onbeforeeditfocus"),
    @XmlEnumValue("ms-onstart")
    MS_ONSTART("ms-onstart"),
    @XmlEnumValue("ms-onfinish")
    MS_ONFINISH("ms-onfinish"),
    @XmlEnumValue("ms-onbounce")
    MS_ONBOUNCE("ms-onbounce"),
    @XmlEnumValue("ms-onbeforeprint")
    MS_ONBEFOREPRINT("ms-onbeforeprint"),
    @XmlEnumValue("ms-onafterprint")
    MS_ONAFTERPRINT("ms-onafterprint"),
    @XmlEnumValue("ms-onpropertychange")
    MS_ONPROPERTYCHANGE("ms-onpropertychange"),
    @XmlEnumValue("ms-onfilterchange")
    MS_ONFILTERCHANGE("ms-onfilterchange"),
    @XmlEnumValue("ms-onreadystatechange")
    MS_ONREADYSTATECHANGE("ms-onreadystatechange"),
    @XmlEnumValue("ms-onlosecapture")
    MS_ONLOSECAPTURE("ms-onlosecapture"),
    @XmlEnumValue("xul-DOMMouseScroll")
    XUL_DOM_MOUSE_SCROLL("xul-DOMMouseScroll"),
    @XmlEnumValue("xul-ondragdrop")
    XUL_ONDRAGDROP("xul-ondragdrop"),
    @XmlEnumValue("xul-ondragenter")
    XUL_ONDRAGENTER("xul-ondragenter"),
    @XmlEnumValue("xul-ondragexit")
    XUL_ONDRAGEXIT("xul-ondragexit"),
    @XmlEnumValue("xul-ondraggesture")
    XUL_ONDRAGGESTURE("xul-ondraggesture"),
    @XmlEnumValue("xul-ondragover")
    XUL_ONDRAGOVER("xul-ondragover"),
    @XmlEnumValue("xul-CheckboxStateChange")
    XUL_CHECKBOX_STATE_CHANGE("xul-CheckboxStateChange"),
    @XmlEnumValue("xul-RadioStateChange")
    XUL_RADIO_STATE_CHANGE("xul-RadioStateChange"),
    @XmlEnumValue("xul-onclose")
    XUL_ONCLOSE("xul-onclose"),
    @XmlEnumValue("xul-oncommand")
    XUL_ONCOMMAND("xul-oncommand"),
    @XmlEnumValue("xul-oninput")
    XUL_ONINPUT("xul-oninput"),
    @XmlEnumValue("xul-DOMMenuItemActive")
    XUL_DOM_MENU_ITEM_ACTIVE("xul-DOMMenuItemActive"),
    @XmlEnumValue("xul-DOMMenuItemInactive")
    XUL_DOM_MENU_ITEM_INACTIVE("xul-DOMMenuItemInactive"),
    @XmlEnumValue("xul-oncontextmenu")
    XUL_ONCONTEXTMENU("xul-oncontextmenu"),
    @XmlEnumValue("xul-onoverflow")
    XUL_ONOVERFLOW("xul-onoverflow"),
    @XmlEnumValue("xul-onoverflowchanged")
    XUL_ONOVERFLOWCHANGED("xul-onoverflowchanged"),
    @XmlEnumValue("xul-onunderflow")
    XUL_ONUNDERFLOW("xul-onunderflow"),
    @XmlEnumValue("xul-onpopuphidden")
    XUL_ONPOPUPHIDDEN("xul-onpopuphidden"),
    @XmlEnumValue("xul-onpopuphiding")
    XUL_ONPOPUPHIDING("xul-onpopuphiding"),
    @XmlEnumValue("xul-onpopupshowing")
    XUL_ONPOPUPSHOWING("xul-onpopupshowing"),
    @XmlEnumValue("xul-onpopupshown")
    XUL_ONPOPUPSHOWN("xul-onpopupshown"),
    @XmlEnumValue("xul-onbroadcast")
    XUL_ONBROADCAST("xul-onbroadcast"),
    @XmlEnumValue("xul-oncommandupdate")
    XUL_ONCOMMANDUPDATE("xul-oncommandupdate");
    private final String value;

    EventTypeList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventTypeList fromValue(String v) {
        for (EventTypeList c: EventTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
