//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.08 at 08:58:06 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openkoncept.net/schema/vroom-config/3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.openkoncept.vroom.config;
