/*
 * VroomFrameworkSettingPanel.java
 *
 * Created on August 12, 2008, 9:58 AM
 */

package net.openkoncept.vroom.plugin.framework;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import org.netbeans.api.project.libraries.Library;
import org.netbeans.api.project.libraries.LibraryManager;

/**
 *
 * @author  fijaz
 */
public class VroomFrameworkSettingPanel extends javax.swing.JPanel {

    /** Creates new form VroomFrameworkSettingPanel */
    public VroomFrameworkSettingPanel() {
        initComponents();
        Library[] libs = LibraryManager.getDefault().getLibraries();
        Vector<String> items = new Vector<String>();
        for(Library lib : libs) {
            String libName = lib.getName();
            if(libName.contains("Vroom")) {
                items.add(libName);
            }
        }
        cbxVroomLibrary.setModel(new DefaultComboBoxModel(items));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVroomFilterMapping = new javax.swing.JLabel();
        txtVroomFilterMapping = new javax.swing.JTextField();
        lblVroomConfigFileName = new javax.swing.JLabel();
        txtVroomConfigFileName = new javax.swing.JTextField();
        lblFileUploadMaxSize = new javax.swing.JLabel();
        txtFileUploadMaxSize = new javax.swing.JTextField();
        lblFileUploadTempLocation = new javax.swing.JLabel();
        txtFileUploadTempLocation = new javax.swing.JTextField();
        lblNoteText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxVroomLibrary = new javax.swing.JComboBox();

        lblVroomFilterMapping.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.lblVroomFilterMapping.text")); // NOI18N

        txtVroomFilterMapping.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.txtVroomFilterMapping.text")); // NOI18N

        lblVroomConfigFileName.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.lblVroomConfigFileName.text")); // NOI18N

        txtVroomConfigFileName.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.txtVroomConfigFileName.text")); // NOI18N

        lblFileUploadMaxSize.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.lblFileUploadMaxSize.text")); // NOI18N

        txtFileUploadMaxSize.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.txtFileUploadMaxSize.text")); // NOI18N

        lblFileUploadTempLocation.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.lblFileUploadTempLocation.text")); // NOI18N

        txtFileUploadTempLocation.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.txtFileUploadTempLocation.text")); // NOI18N

        lblNoteText.setForeground(new java.awt.Color(153, 51, 0));
        lblNoteText.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.lblNoteText.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(VroomFrameworkSettingPanel.class, "VroomFrameworkSettingPanel.jLabel1.text")); // NOI18N

        cbxVroomLibrary.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileUploadMaxSize)
                    .addComponent(lblFileUploadTempLocation)
                    .addComponent(lblVroomConfigFileName)
                    .addComponent(lblVroomFilterMapping)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoteText, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFileUploadTempLocation, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFileUploadMaxSize, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtVroomConfigFileName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVroomFilterMapping, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(cbxVroomLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxVroomLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVroomFilterMapping)
                    .addComponent(txtVroomFilterMapping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVroomConfigFileName)
                    .addComponent(txtVroomConfigFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFileUploadMaxSize)
                    .addComponent(txtFileUploadMaxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileUploadTempLocation)
                    .addComponent(txtFileUploadTempLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNoteText)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxVroomLibrary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFileUploadMaxSize;
    private javax.swing.JLabel lblFileUploadTempLocation;
    private javax.swing.JLabel lblNoteText;
    private javax.swing.JLabel lblVroomConfigFileName;
    private javax.swing.JLabel lblVroomFilterMapping;
    private javax.swing.JTextField txtFileUploadMaxSize;
    private javax.swing.JTextField txtFileUploadTempLocation;
    private javax.swing.JTextField txtVroomConfigFileName;
    private javax.swing.JTextField txtVroomFilterMapping;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtFileUploadMaxSize() {
        return txtFileUploadMaxSize;
    }

    public javax.swing.JTextField getTxtFileUploadTempLocation() {
        return txtFileUploadTempLocation;
    }

    public javax.swing.JTextField getTxtVroomConfigFileName() {
        return txtVroomConfigFileName;
    }

    public javax.swing.JTextField getTxtVroomFilterMapping() {
        return txtVroomFilterMapping;
    }

    public void setTxtFileUploadMaxSize(javax.swing.JTextField txtFileUploadMaxSize) {
        this.txtFileUploadMaxSize = txtFileUploadMaxSize;
    }

    public void setTxtFileUploadTempLocation(javax.swing.JTextField txtFileUploadTempLocation) {
        this.txtFileUploadTempLocation = txtFileUploadTempLocation;
    }

    public void setTxtVroomConfigFileName(javax.swing.JTextField txtVroomConfigFileName) {
        this.txtVroomConfigFileName = txtVroomConfigFileName;
    }

    public void setTxtVroomFilterMapping(javax.swing.JTextField txtVroomFilterMapping) {
        this.txtVroomFilterMapping = txtVroomFilterMapping;
    }

    public javax.swing.JComboBox getCbxVroomLibrary() {
        return cbxVroomLibrary;
    }

    public void setCbxVroomLibrary(javax.swing.JComboBox cbxVroomLibrary) {
        this.cbxVroomLibrary = cbxVroomLibrary;
    }

}
